// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCore_Practice.Database_First_Migration
{
    public partial class Guilds
    {
        public Guilds()
        {
            Players = new HashSet<Players>();
        }

        public int GuildId { get; set; }
        public string GuildName { get; set; }

        public virtual ICollection<Players> Players { get; set; }
    }
}