// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCore_Practice.Database_First_Migration
{
    public partial class Items
    {
        public int ItemId { get; set; }
        public bool IsDeleted { get; set; }
        public int TypeId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int OwnerId { get; set; }
        public int ItemGrade { get; set; }

        public virtual Players Owner { get; set; }
    }
}