// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCore_Practice.Database_First_Migration
{
    public partial class Players
    {
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public int Test { get; set; }
        public int? GuildId { get; set; }

        public virtual Guilds Guild { get; set; }
        public virtual Items Items { get; set; }
    }
}